export default {
  dbName: 'MONGODB_USERNAME',
  dbPass: 'MONGODB_PASSWORD',
  accessTokenPrivateKey: 'ACCESS_TOKEN_PRIVATE_KEY',
  accessTokenPublicKey: 'ACCESS_TOKEN_PUBLIC_KEY',
  refreshTokenPrivateKey: 'REFRESH_TOKEN_PRIVATE_KEY',
  refreshTokenPublicKey: 'REFRESH_TOKEN_PUBLIC_KEY',
  mongoUrl: 'MONGO_URL',
  port: 'PORT',
  redisPort: 'REDIS_PORT',
  redisHost: 'REDIS_HOST',
  bullMQRedisDB: 'BULLMQ_REDIS_DB',
  redisDB: 'REDIS_DB',
  redisMaxStreamLength: 'REDIS_MAX_STREAM_LENGTH',
  bullMQRedisRemoveCompleteCount:'BULLMQ_REDIS_REMOVE_COMPLETE_COUNT',
  bullMQRedisRemoveFailCount: 'BULLMQ_REDIS_REMOVE_FAIL_COUNT',
};
